name: e14_client
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  shared_preferences: ^2.2.2
  dio: ^5.3.3
  wakelock: ^0.6.2
  socket_io_client: ^2.0.3+1
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  camera: ^0.10.5+5

  flutter_svg: ^2.0.8
  animations: ^2.0.8

  fluttertoast: ^8.2.2
  flutter_local_notifications: ^16.1.0
  firebase_core: ^2.20.0
  firebase_messaging: ^14.7.2

  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true